name: Flacon
markdown: kramdown
highlighter: rouge
baseurl:
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
flacon:
  release:
    version: 5.5.0
    link: https://github.com/flacon/flacon/archive
