name: Flacon
markdown: redcarpet
pygments: true
baseurl:
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
flacon:
  release:
    version: 0.9.4
    link: https://github.com/flacon/flacon/archive/v0.9.4.tar.gz
