name: Flacon
markdown: redcarpet
highlighter: pygments
baseurl:
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
flacon:
  release:
    version: 2.0.0
    link: https://github.com/flacon/flacon/archive
