#!/bin/bash

#convert flacon-1.png -resize 600x9999 flacon-1-small.png

SIZE=600x9999

convert flacon-config.png  -resize ${SIZE}  flacon-config-small.png
convert flacon-convert.png -resize ${SIZE} flacon-convert-small.png
convert flacon-cover.png   -resize ${SIZE} flacon-cover-small.png
convert flacon-main.png    -resize ${SIZE} flacon-main-small.png

